use super::*;
use MeasurementUnit::*;
use QuantityKind::*;

fn close(actual: f64, expected: f64) {
    assert!(
        (actual - expected).abs() <= 1e-12 * expected.abs().max(1.0),
        "{actual} != {expected}"
    );
}

#[test]
fn independent_reference_values_cover_temperature_pressure_flow_and_existing_results() {
    // Independent reference values, not generated by the conversion implementation.
    for (q, from, to, value, expected) in [
        (AbsoluteTemperature, Celsius, Kelvin, 0.0, 273.15),
        (AbsoluteTemperature, Celsius, Kelvin, 100.0, 373.15),
        (AbsoluteTemperature, Kelvin, Celsius, 300.0, 26.85),
        (
            TemperatureDifference,
            CelsiusDifference,
            KelvinDifference,
            10.0,
            10.0,
        ),
        (
            TemperatureDifference,
            KelvinDifference,
            CelsiusDifference,
            -5.0,
            -5.0,
        ),
        (AbsolutePressure, Bar, Pascal, 1.0, 100_000.0),
        (AbsolutePressure, Megapascal, Kilopascal, 0.25, 250.0),
        (AbsolutePressure, Pascal, Bar, 90_000.0, 0.9),
        (MolarFlow, KilomolePerHour, MolePerSecond, 3.6, 1.0),
        (MolarFlow, MolePerSecond, KilomolePerHour, 5.0, 18.0),
        (MolarFlow, MolePerHour, MolePerSecond, 3600.0, 1.0),
        (MolarFlow, KilomolePerSecond, MolePerSecond, 0.001, 1.0),
        (MoleFraction, MolePercent, MolePerMole, 35.0, 0.35),
        (MolarPhaseFraction, MolePerMole, MolePercent, 0.8, 80.0),
        (MolarEnthalpy, KilojoulePerMole, JoulePerMole, -2.5, -2500.0),
    ] {
        close(convert(value, q, from, to).unwrap(), expected);
    }
}

#[test]
fn absolute_temperature_and_difference_cannot_share_an_offset_by_accident() {
    assert_eq!(
        AbsoluteTemperature.definition().dimension,
        TemperatureDifference.definition().dimension
    );
    for (q, unit) in [
        (AbsoluteTemperature, CelsiusDifference),
        (TemperatureDifference, Celsius),
    ] {
        assert_eq!(
            to_canonical(10.0, q, unit),
            Err(ConversionError::IncompatibleUnit { quantity: q, unit })
        );
    }
    assert_eq!(resolve_unit(AbsoluteTemperature, "°C"), Ok(Celsius));
    assert_eq!(
        resolve_unit(TemperatureDifference, "°C"),
        Ok(CelsiusDifference)
    );
    assert_eq!(
        resolve_unit(TemperatureDifference, "K"),
        Ok(KelvinDifference)
    );
    // Conversion preserves the mathematical value. Physical positivity belongs to the variable.
    close(
        to_canonical(-300.0, AbsoluteTemperature, Celsius).unwrap(),
        -26.85,
    );
}

#[test]
fn contextual_units_never_use_assumed_reference_conditions() {
    for (q, unit, alias, requirement) in [
        (
            AbsolutePressure,
            BarGauge,
            "barg",
            ContextRequirement::ReferencePressure,
        ),
        (
            MolarFlow,
            KilogramPerSecond,
            "kg/s",
            ContextRequirement::MixtureMolarMass,
        ),
        (
            MolarFlow,
            StandardCubicMetrePerHour,
            "Nm3/h",
            ContextRequirement::StandardVolumeBasisAndStateRelation,
        ),
    ] {
        let error = ConversionError::ContextRequired { unit, requirement };
        assert_eq!(to_canonical(1.0, q, unit).unwrap_err(), error);
        assert_eq!(from_canonical(1.0, q, unit).unwrap_err(), error);
        assert_eq!(convert(1.0, q, unit, unit).unwrap_err(), error);
        assert_eq!(resolve_unit(q, alias).unwrap_err(), error);
        assert!(!q.definition().units.contains(&unit));
    }
    assert!(matches!(
        to_canonical(1.0, AbsoluteTemperature, BarGauge),
        Err(ConversionError::IncompatibleUnit { .. })
    ));
}

#[test]
fn catalog_ids_aliases_dimensions_and_canonical_units_are_consistent() {
    let mut ids = std::collections::HashSet::new();
    let mut units = std::collections::HashSet::new();
    for &unit in ALL_UNITS {
        assert!(units.insert(unit));
        assert!(ids.insert(unit.definition().id));
    }
    let mut quantity_ids = std::collections::HashSet::new();
    for &q in ALL_QUANTITIES {
        let d = q.definition();
        assert!(quantity_ids.insert(d.id));
        assert_eq!(d.units[0], d.canonical_unit);
        assert_eq!(
            d.canonical_unit.definition().conversion,
            ConversionRule::Affine {
                scale: 1.0,
                offset: 0.0
            }
        );
        let mut tokens = std::collections::HashMap::new();
        for &unit in d.units {
            let u = unit.definition();
            assert_eq!(u.dimension, d.dimension);
            for token in std::iter::once(u.id)
                .chain(std::iter::once(u.symbol))
                .chain(u.aliases.iter().copied())
            {
                if let Some(previous) = tokens.insert(token, unit) {
                    assert_eq!(previous, unit, "ambiguous alias {token}");
                }
                assert_eq!(resolve_unit(q, token), Ok(unit));
            }
            let ConversionRule::Affine { scale, offset } = u.conversion else {
                panic!("contextual unit listed as supported")
            };
            assert!(scale.is_finite() && scale > 0.0 && offset.is_finite());
        }
    }
}

#[test]
fn conversion_rejects_invalid_units_non_finite_values_and_overflow() {
    assert!(matches!(
        resolve_unit(MolarFlow, "bogus"),
        Err(ConversionError::UnknownUnit { .. })
    ));
    assert!(matches!(
        resolve_unit(AbsolutePressure, "pa"),
        Err(ConversionError::UnknownUnit { .. })
    ));
    assert_eq!(resolve_unit(AbsolutePressure, "  kPa  "), Ok(Kilopascal));
    assert!(matches!(
        convert(1.0, AbsolutePressure, Pascal, Celsius),
        Err(ConversionError::IncompatibleUnit { .. })
    ));
    for value in [f64::NAN, f64::INFINITY, f64::NEG_INFINITY] {
        assert_eq!(
            to_canonical(value, AbsoluteTemperature, Kelvin),
            Err(ConversionError::NonFiniteValue)
        );
    }
    assert_eq!(
        to_canonical(f64::MAX, AbsolutePressure, Bar),
        Err(ConversionError::Overflow)
    );
    assert_eq!(
        from_canonical(f64::MAX, MolarFlow, MolePerHour),
        Err(ConversionError::Overflow)
    );
}

#[test]
fn equivalent_and_round_trip_conversions_preserve_computation_precision() {
    for &q in ALL_QUANTITIES {
        for &unit in q.definition().units {
            for value in [-10.0, 0.0, 0.123456789012345, 1.0, 300.123456789, 1e10] {
                let canonical = to_canonical(value, q, unit).unwrap();
                close(from_canonical(canonical, q, unit).unwrap(), value);
            }
            let value = 0.00000000000000000001;
            assert_eq!(
                convert(value, q, unit, unit).unwrap().to_bits(),
                value.to_bits()
            );
            assert_eq!(
                convert(-0.0, q, unit, unit).unwrap().to_bits(),
                (-0.0_f64).to_bits()
            );
        }
    }
}
